name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Sync with Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email "jaikushwaha7@gmail.com"
        git config --global user.name "jaikushwaha7"

        # Clone Hugging Face Space outside current dir
        git clone https://huggingface.co/spaces/jaikushwaha7/flight-delay ../hf-space

        # Copy contents of GitHub repo (current directory) into the cloned HF repo
        rsync -av --exclude='.git' ./ ../hf-space/

        cd ../hf-space
        git add .
        git commit -m "🚀 Auto-sync from GitHub" || echo "No changes to commit"
        git push https://huggingface:${HF_TOKEN}@huggingface.co/spaces/jaikushwaha7/flight-delay main
