name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Sync with Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email "jaikushwaha7@gmail.com"
        git config --global user.name "jaikushwaha7"

        mkdir tmp && cp -r . tmp/
        cd tmp

        git clone https://huggingface.co/spaces/jaikushwaha7/flight-delay hf-space
        rm -rf hf-space/* hf-space/.* 2>/dev/null || true  # remove all existing files (including hidden)

        cp -r . hf-space/
        cd hf-space
        git add .
        git commit -m "🚀 Full sync from GitHub (overwrite)" || echo "No changes to commit"
        git push https://huggingface:${HF_TOKEN}@huggingface.co/spaces/jaikushwaha7/flight-delay main
