name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v3

    - name: Sync with Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email "jaikushwaha7@gmail.com"
        git config --global user.name "jaikushwaha7"

        # Clone Hugging Face Space outside current directory
        git clone https://huggingface.co/spaces/jaikushwaha7/flight-delay ../hf-space

        # Copy contents of GitHub repo to Hugging Face Space, excluding large files
        rsync -av \
          --exclude='.git' \
          --exclude='data/raw/flights_sample_100k.csv' \
          --exclude='data/raw/flight-delay-and-cancellation-data-2019-2023-v2.zip' \
          --exclude='data/reports/' \
          --exclude='output_report.html' \
          --exclude='reports/flight_data_profile_report.html'
          --exclude='reports/flight_data_profile_report_pre_processing.html'
          --exclude='wandb/' \
          --exclude='data/raw/flight-delay-and-cancellation-data-2019-2023-v2.zip' \
          ./ ../hf-space/

        cd ../hf-space
        git add .
        git commit -m "🚀 Auto-sync from GitHub" || echo "No changes to commit"
        git push https://huggingface:${HF_TOKEN}@huggingface.co/spaces/jaikushwaha7/flight-delay main
